### ISSUE TITLE
Not working on Xcode 8 - issue "Could not found any Target!"

### ISSUE THREAD

**Issue by socoboy** [krzysztofzablocki/crafter#22]
Hi, I trying to setup a project with Xcode 8, cause issue "Could not found any Target!"

Traceback here:
Duongs-MacBook-Pro:<project_dir> socoboy$ crafter 
/Users/socoboy/workspace/tools/crafter/lib/project_helper.rb:97:in `choose_item': Could not locate any Targets! (RuntimeError)
	from /Users/socoboy/workspace/tools/crafter/lib/project_helper.rb:64:in `select_target_for_name'
	from /Users/socoboy/workspace/tools/crafter/lib/crafter.rb:37:in `find_target_configuration'
	from /Users/socoboy/workspace/tools/crafter/lib/crafter.rb:28:in `with'
	from /Users/socoboy/.crafter.rb:77:in `block in <top (required)>'
	from /Users/socoboy/workspace/tools/crafter/lib/crafter.rb:24:in `instance_eval'
	from /Users/socoboy/workspace/tools/crafter/lib/crafter.rb:24:in `configure'
	from /Users/socoboy/.crafter.rb:4:in `<top (required)>'
	from /Users/socoboy/workspace/tools/crafter/lib/crafter.rb:134:in `load'
	from /Users/socoboy/workspace/tools/crafter/lib/crafter.rb:134:in `<module:Crafter>'
	from /Users/socoboy/workspace/tools/crafter/lib/crafter.rb:13:in `<top (required)>'
	from /Users/socoboy/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/socoboy/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/socoboy/workspace/tools/crafter/bin/crafter:13:in `<main>'

**Comment by alvincrisuy** [comment]
Any information regarding this issue? I'm encountering the same issue.

**Comment by krzysztofzablocki** [comment]
@alvincrisuy try with 0.2 gem

**Comment by AVAlex** [comment]
It does not work like this.
